before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    id: woodpecker
    main: ./cmd/woodpecker
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-X github.com/operantai/woodpecker/cmd/woodpecker/cmd.GitCommit={{.Commit}}"
      - "-X github.com/operantai/woodpecker/cmd/woodpecker/cmd.Version={{.Version}}"
      - "-X github.com/operantai/woodpecker/cmd/woodpecker/cmd.BuildDate={{ .Date }}"
  - env:
      - CGO_ENABLED=0
    id: woodpecker-mcp-verifier
    main: ./cmd/woodpecker-mcp-verifier
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-X github.com/operantai/woodpecker/cmd/woodpecker-mcp-verifier/cmd.GitCommit={{.Commit}}"
      - "-X github.com/operantai/woodpecker/cmd/woodpecker-mcp-verifier/cmd.Version={{.Version}}"
      - "-X github.com/operantai/woodpecker/cmd/woodpecker-mcp-verifier/cmd.BuildDate={{ .Date }}"

archives:
  - formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: [ zip ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
